### PR TITLE
fix: support mistralai 2.0.0 import change

### LINKED ISSUE #2137: bug: New Mistralai version 2.0.0 released 3h ago breaks instructor
- [x] This is actually a bug report.

**Describe the bug**
New Mistralai version 2.0.0 released 3h ago breaks instructor:

  File "/home/runner/work/.venv/lib/python3.10/site-packages/instructor/providers/__init__.py", line 55, in <module>
    from .mistral.client import from_mistral  # noqa: F401
  File "/home/runner/work/.venv/lib/python3.10/site-packages/instructor/providers/mistral/client.py", line 5, in <module>
    from mistralai import Mistral
ImportError: cannot import name 'Mistral' from 'mistralai' (unknown location)

Mistralai seems to have changed their import. from mistralai import Mistral is no longer valid. This causes instructor not to work for other providers as well if mistral is installed.

**To Reproduce**
Install latest mistralai version 2.0.0 and try using instructor 1.14.5

### PR DESCRIPTION
**Pull request by giulio-leone**
## Summary

Fixes #2137

`mistralai` 2.0.0 (released 2 days ago) moved the `Mistral` class from `mistralai.Mistral` to `mistralai.client.Mistral`, causing an `ImportError` that breaks `instructor` — even for users not using Mistral — because the import runs at module load time.

## Changes

| File | Change |
|---|---|
| `instructor/providers/mistral/client.py` | Try `from mistralai import Mistral`, fall back to `from mistralai.client import Mistral` |
| `instructor/auto_client.py` | Same try/except pattern for the auto-client Mistral import |
| `instructor/providers/__init__.py` | Wrap mistral import in try/except to prevent entire providers module from breaking |

## Testing

- Verified import works with **mistralai 2.0.0** (new import path)
- Verified backward compatibility with **mistralai 1.10.0** (old import path)
- All existing tests pass (no regressions)

### CODE REVIEW

**Comment by giulio-leone** [comment]
Hi @jxnl @ivanleomk — friendly ping on this PR. It fixes the `mistralai` 2.0.0 import change (`from mistralai import Mistral` → `from mistralai.client import MistralClient` compatibility). The fix is backward-compatible and covers both the old and new import paths. Would appreciate a review when you have a moment. Thanks!

**Comment by jxnl** [comment]
Duplicate of #2152. I’m keeping a single canonical PR open for issue #2137 and using #2152 for that path so we don’t carry multiple overlapping Mistral v2 fixes.
