### ISSUE TITLE
support nested Annotated and set

### ISSUE THREAD

**Issue by wciq1208** [jxnl/instructor#917]
**Is your feature request related to a problem? Please describe.**
for explame
```python
class MyModel(BaseModel):
    my_list: List[constr(max_length=10)]

openai_client = OpenAI(
        base_url="http://192.168.91.25:8000/v1",
        api_key="EMPTY",
    )
client = instructor.from_openai(openai_client)

resp = client.chat.completions.create(
        model="/model/Qwen1.5-14B-Chat-GPTQ-Int4",
        messages=[{"role": "user",
                   "content": "generator random keywords"}],
        response_model=MyModel,
        extra_body={
            "guided_decoding_backend": "lm-format-enforcer"
        }
    )
```

current error output
```bash
Traceback (most recent call last):
  File "/Users/cyberserval/PycharmProjects/hestia/test_instructor.py", line 50, in <module>
    resp = client.chat.completions.create(
  File "/Users/cyberserval/PycharmProjects/hestia/venv/lib/python3.10/site-packages/instructor/client.py", line 116, in create
    return self.create_fn(
  File "/Users/cyberserval/PycharmProjects/hestia/venv/lib/python3.10/site-packages/instructor/patch.py", line 140, in new_create_sync
    response_model, new_kwargs = handle_response_model(
  File "/Users/cyberserval/PycharmProjects/hestia/venv/lib/python3.10/site-packages/instructor/process_response.py", line 239, in handle_response_model
    response_model = openai_schema(response_model)  # type: ignore
  File "/Users/cyberserval/PycharmProjects/hestia/venv/lib/python3.10/site-packages/instructor/function_calls.py", line 498, in openai_schema
    return openai_schema_helper(cls)
  File "/Users/cyberserval/PycharmProjects/hestia/venv/lib/python3.10/site-packages/instructor/function_calls.py", line 475, in openai_schema_helper
    new_field_type = openai_schema_helper(field_type)
  File "/Users/cyberserval/PycharmProjects/hestia/venv/lib/python3.10/site-packages/instructor/function_calls.py", line 460, in openai_schema_helper
    return list[openai_schema_helper(cls.__args__[0])]
  File "/Users/cyberserval/PycharmProjects/hestia/venv/lib/python3.10/site-packages/instructor/function_calls.py", line 468, in openai_schema_helper
    if issubclass(cls, (str, int, bool, float, bytes, Enum)):
TypeError: issubclass() arg 1 must be a class
```

**Describe the solution you'd like**
get payload
```json
{
    "messages": [
        {
            "role": "user",
            "content": "generator random keywords"
        }
    ],
    "model": "/model/Qwen1.5-14B-Chat-GPTQ-Int4",
    "extra_body": {
        "guided_decoding_backend": "lm-format-enforcer"
    },
    "tools": [
        {
            "type": "function",
            "function": {
                "name": "MyModel",
                "description": "Correctly extracted `MyModel` with all the required parameters with correct types",
                "parameters": {
                    "properties": {
                        "keywords": {
                            "items": {
                                "minLength": 10,
                                "type": "string"
                            },
                            "title": "Keywords",
                            "type": "array"
                        }
                    },
                    "required": [
                        "keywords"
                    ],
                    "type": "object"
                }
            }
        }
    ],
    "tool_choice": {
        "type": "function",
        "function": {
            "name": "MyModel"
        }
    }
}
```

**Describe alternatives you've considered**
Insert this piece of code right before the if issubclass(cls, (str, int, bool, float, bytes, Enum)) statement within the openai_schema_helper function.
```python
if origin is set:
    return set[openai_schema_helper(cls.__args__[0])]
if origin is Annotated:
    return cls
```

**Additional context**

**Comment by ivanleomk** [comment]
Hi @wciq1208 , this is my fault - I introduced a feature that modifies the base model class in v1.5. My goal is to publish a fix soon but I'm working on making sure it's well tested. 

```
from pydantic import BaseModel, Field
import openai
import instructor


class MyModel(BaseModel):
    my_list: list[str] = Field(max_length=10, min_length=10)


client = instructor.from_openai(openai.OpenAI())

resp = client.chat.completions.create(
    messages=[
        {
            "role": "system",
            "content": "You are a helpful assistant that generates 10 random keywords",
        }
    ],
    response_model=MyModel,
    max_retries=3,
    model="gpt-4o-mini",
)
```

This works nicely for instance with the openai library ( and probably ollama/llama-cpp if that's what you're using locally). If not, I recommend dowgrading to 1.4 or 1.5 before this new BaseModel change was introduced

**Comment by economy** [comment]
@ivanleomk not sure which version you're referring to, I'm getting the same issue on 1.3.4 and 1.3.7 (the latest version)

**Comment by 97k** [comment]
I am facing the same issue with instructor 1.3.5 +
all of my schemas (basemodels) uses Union, Optional and List. 

There is problem with `openai_schema_helper` in `function_calls.py`

I upgraded as I wanted to use the async validators.

**Comment by 97k** [comment]
@economy v1.3.4 works fine for me.

**Comment by ivanleomk** [comment]
@wciq1208 I just released instructor 1.4.0, this should fix this issue. Could you try it and give it a shot?

**Comment by ivanleomk** [comment]
Awesome! Also as a heads up, we also have support for structured outputs too if you wanna try it with `TOOLS_STRICT` :)

**Comment by wciq1208** [comment]
> @wciq1208 I just released instructor 1.4.0, this should fix this issue. Could you try it and give it a shot?

It works well, thank you!

**Comment by 97k** [comment]
@ivanleomk with 1.4.0 I am getting following error
`Attribute Error: 'ChatCompletionMessage' object has no attribute 'refusal'`

This worked fine with v1.3.4

**Comment by ivanleomk** [comment]
Can you attach a copy of the code you’re using. The refusal object should
be defined on the new OpenAI client.

**Comment by 97k** [comment]
@ivanleomk sure, here's the basic version which will help in reproducing the error.

```python
import instructor
from groq import Groq
from app import settings

client = instructor.from_groq(
                client=Groq(
                    api_key=settings.GROQ_API_KEY.get_secret_value(), max_retries=5
                ))

class Property(BaseModel):
    name: str = Field(description="The name of the person")
    age: int = Field(description="The age of the person")

resp = client.chat.completions.create(
    response_model=Property,
    model="llama3-70b-8192",
    messages=[
        {"role": "system", "content": "Extract name and age from the message"},
        {"role": "user", "content": "I am aditya and I am 1000 years old"}
        ]
)

```

Here's the error raised
```
AttributeError                            Traceback (most recent call last)
File ~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/retry.py:164, in retry_sync(func, response_model, validation_context, args, kwargs, max_retries, strict, mode)
    [163](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/retry.py:163)     response = update_total_usage(response, total_usage)
--> [164](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/retry.py:164)     return process_response(
    [165](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/retry.py:165)         response,
    [166](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/retry.py:166)         response_model=response_model,
    [167](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/retry.py:167)         stream=stream,
    [168](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/retry.py:168)         validation_context=validation_context,
    [169](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/retry.py:169)         strict=strict,
    [170](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/retry.py:170)         mode=mode,
    [171](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/retry.py:171)     )
    [172](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/retry.py:172) except (ValidationError, JSONDecodeError) as e:

File ~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/process_response.py:144, in process_response(response, response_model, stream, validation_context, strict, mode)
    [142](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/process_response.py:142)     return model
--> [144](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/process_response.py:144) model = response_model.from_response(
    [145](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/process_response.py:145)     response,
    [146](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/process_response.py:146)     validation_context=validation_context,
    [147](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/process_response.py:147)     strict=strict,
    [148](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/process_response.py:148)     mode=mode,
    [149](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/process_response.py:149) )
    [151](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/process_response.py:151) # ? This really hints at the fact that we need a better way of
    [152](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/process_response.py:152) # ? attaching usage data and the raw response to the model we return.

File ~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/function_calls.py:149, in OpenAISchema.from_response(cls, completion, validation_context, strict, mode)
    [148](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/function_calls.py:148) if mode in {Mode.TOOLS, Mode.MISTRAL_TOOLS, Mode.TOOLS_STRICT}:
--> [149](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/function_calls.py:149)     return cls.parse_tools(completion, validation_context, strict)
    [151](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/function_calls.py:151) if mode in {Mode.JSON, Mode.JSON_SCHEMA, Mode.MD_JSON}:

File ~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/function_calls.py:318, in OpenAISchema.parse_tools(cls, completion, validation_context, strict)
    [314](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/function_calls.py:314) assert (
    [315](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/function_calls.py:315)     len(message.tool_calls or []) == 1
    [316](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/function_calls.py:316) ), "Instructor does not support multiple tool calls, use List[Model] instead."
    [317](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/function_calls.py:317) assert (
--> [318](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/function_calls.py:318)     message.refusal is None
    [319](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/function_calls.py:319) ), f"Unable to generate a response due to {message.refusal}"
    [320](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/instructor/function_calls.py:320) tool_call = message.tool_calls[0]  # type: ignore

File ~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/pydantic/main.py:828, in BaseModel.__getattr__(self, item)
    [826](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/pydantic/main.py:826) else:
    [827](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/pydantic/main.py:827)     # this is the current error
--> [828](https://file+.vscode-resource.vscode-cdn.net/Users/ad/exp/AIConcierge/building_blocks/nbs/~/opt/miniconda3/envs/dev/lib/python3.10/site-packages/pydantic/main.py:828)     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')

AttributeError: 'ChatCompletionMessage' object has no attribute 'refusal'


```

> While version 1.3.4 worked falwlessly!

**Comment by ivanleomk** [comment]
Ah ok you're not using the OpenAI providers but groq. I didn't account for that. 

We added the refusal here in accordance with their new api standard. 

https://github.com/openai/openai-python/blob/main/src/openai/types/chat/chat_completion_message.py#L25-L43

**Comment by 97k** [comment]
Exactly, this breaks the groq support. 
I downgraded to 1.3.4 again.

**Comment by 97k** [comment]
@ivanleomk would we create a new issue from this?

**Comment by ivanleomk** [comment]
Yes let’s do that. I’ll close this issue first

**Comment by ivanleomk** [comment]
@97k created a new issue to track it here https://github.com/jxnl/instructor/issues/953
